### ISSUE TITLE
can you write a demo ? thank you

### ISSUE THREAD

**Issue by ghost** [Paldom/angular2-rest#5]
i used it
it can not work
can you write a demo ? thank you

**Comment by ghost** [comment]
var a=new TodoRESTClient()
alert(a.getTodos())

**Comment by Paldom** [comment]
I'm wokring on a demo, but it needs more time than I thought. Hope to finish it shortly.

**Comment by ghost** [comment]
thank you very much,i used http://jsonplaceholder.typicode.com/  testting my project :)

**Comment by mmrath** [comment]
I have created a [plunker](http://plnkr.co/edit/tCRoSFAWVUP9BoPvMA2U?p=preview). See if it helps

**Comment by ghost** [comment]
@mmrath thank you very much :)

**Comment by NicolasCayet** [comment]
Hi,
First of all, thanks for your module. That's the only REST module i've found for Angular2.

But I'm a bit confused. Your joined plunker is not relevant, because it does not show a proper usage as a node module.

I've included the angular2-rest/angular2-rest.js file in my index.html <head> and I'm stuck on an "Uncaught ReferenceError: require is not defined" (angular2-rest.js:46)

Can you provide more example please ? At least, a simple usage considering angular2-rest has been installed with `npm install` ?

**Comment by NicolasCayet** [comment]
After some time of workaround, I finally decided to use the code present in `angular2-rest.ts` you shared on Plunker, including it as a .ts file in my project (building it with the rest of my application), and it works !

It seems the version available among NPM is not up-to-date.

I'm still interested to deploy your solution as a node module (through NPM), and hope you'll can provide more information about how to use it.
